# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.cyclenet.ipynb.

# %% auto 0
__all__ = ["RecurrentCycle", "CycleNet"]

# %% ../../nbs/models.cyclenet.ipynb 5
from typing import Optional

import torch
import torch.nn as nn

from ..common._base_model import BaseModel
from ..losses.pytorch import MAE

# Upstream references used for this port:
# - Core model (official): https://github.com/ACAT-SCUT/CycleNet/blob/main/models/CycleNet.py
# - Cycle index generation note (official): https://github.com/ACAT-SCUT/CycleNet/blob/main/README.md#model-implementation


# %% ../../nbs/models.cyclenet.ipynb 8
class RecurrentCycle(nn.Module):
    """Learnable recurrent cycle bank Q in the CycleNet paper.

    Parameter mapping to upstream `RecurrentCycle`:
    - `cycle_len`  <-> upstream `cycle_len`
    - `channel_size` <-> upstream `channel_size`
    - `self.data` initialized to zeros as in upstream.
    """

    def __init__(self, cycle_len: int, channel_size: int):
        super().__init__()
        self.cycle_len = cycle_len
        self.channel_size = channel_size
        self.data = nn.Parameter(
            torch.zeros(cycle_len, channel_size), requires_grad=True
        )

    def forward(self, index: torch.Tensor, length: int) -> torch.Tensor:
        gather_index = (
            index.view(-1, 1)
            + torch.arange(length, device=index.device, dtype=index.dtype).view(1, -1)
        ) % self.cycle_len
        return self.data[gather_index]


# %% ../../nbs/models.cyclenet.ipynb 10
class CycleNet(BaseModel):
    """CycleNet

    CycleNet implements Residual Cycle Forecasting (RCF) by learning a recurrent
    cycle table and forecasting residuals with either a Linear or an MLP head.

    *Parameters:*<br>
    `h`: int, forecast horizon.<br>
    `input_size`: int, maximum sequence length for truncated train backpropagation.<br>
    `cycle_len`: int, period length W of the learnable recurrent cycle.<br>
    `cycle_index_col`: str=None, optional future exogenous column containing the
    absolute cycle index for each timestamp (e.g. `t mod cycle_len`).<br>
    `model_type`: str='linear', backbone type in {'linear', 'mlp'}.<br>
    `d_model`: int=64, hidden size when `model_type='mlp'`.<br>
    `use_revin`: bool=True, apply instance normalization and de-normalization.<br>
    `stat_exog_list`: str list, static exogenous columns.<br>
    `hist_exog_list`: str list, historic exogenous columns.<br>
    `futr_exog_list`: str list, future exogenous columns.<br>
    `exclude_insample_y`: bool=False, skips autoregressive features if True.<br>
    `loss`: PyTorch module, instantiated train loss.<br>
    `valid_loss`: PyTorch module=`loss`, instantiated valid loss.<br>
    `max_steps`: int=1000, maximum number of training steps.<br>
    `learning_rate`: float=1e-3, Learning rate between (0, 1).<br>
    `num_lr_decays`: int=-1, number of learning rate decays.<br>
    `early_stop_patience_steps`: int=-1, number of validation iterations before early stopping.<br>
    `val_check_steps`: int=100, training steps between validation checks.<br>
    `batch_size`: int=32, number of different series in each batch.<br>
    `valid_batch_size`: int=None, validation batch size; if None uses batch_size.<br>
    `windows_batch_size`: int=1024, windows sampled in each training batch.<br>
    `inference_windows_batch_size`: int=1024, windows sampled in each inference batch.<br>
    `start_padding_enabled`: bool=False, if True pad beginning with zeros by input_size.<br>
    `step_size`: int=1, step size between each temporal window.<br>
    `scaler_type`: str='identity', type of temporal scaler.<br>
    `random_seed`: int=1, random seed for initializers and generators.<br>
    `drop_last_loader`: bool=False, if True drop last non-full batch.<br>
    `alias`: str=None, optional custom name.<br>
    `optimizer`: optional custom optimizer class.<br>
    `optimizer_kwargs`: dict, optional optimizer kwargs.<br>
    `lr_scheduler`: optional custom lr scheduler class.<br>
    `lr_scheduler_kwargs`: dict, optional scheduler kwargs.<br>
    `dataloader_kwargs`: dict, optional dataloader kwargs.<br>
    `**trainer_kwargs`: keyword args inherited from PyTorch Lightning trainer.<br>

    Upstream parameter mapping (`models/CycleNet.py`, class `Model`):
    - `input_size` -> upstream `seq_len`
    - `h` -> upstream `pred_len`
    - `cycle_len` -> upstream `cycle`
    - `model_type` -> upstream `model_type` ('linear' | 'mlp')
    - `d_model` -> upstream `d_model` (used only for MLP)
    - `use_revin` -> upstream `use_revin`

    Note on cycle index:
    - Upstream dataloader passes `cycle_index` per sample (`t mod W`).
    - In NeuralForecast we read the same value from `cycle_index_col` inside
      `futr_exog` to keep the model API compatible with BaseModel.
    """

    EXOGENOUS_FUTR = True
    EXOGENOUS_HIST = False
    EXOGENOUS_STAT = False
    MULTIVARIATE = False
    RECURRENT = False

    def __init__(
        self,
        h: int,
        input_size: int,
        cycle_len: int,
        cycle_index_col: Optional[str] = None,
        model_type: str = "linear",
        d_model: int = 64,
        use_revin: bool = True,
        stat_exog_list=None,
        hist_exog_list=None,
        futr_exog_list=None,
        exclude_insample_y: bool = False,
        loss=MAE(),
        valid_loss=None,
        max_steps: int = 5000,
        learning_rate: float = 1e-4,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        windows_batch_size=1024,
        inference_windows_batch_size=1024,
        start_padding_enabled: bool = False,
        step_size: int = 1,
        scaler_type: str = "identity",
        random_seed: int = 1,
        drop_last_loader: bool = False,
        alias: Optional[str] = None,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        dataloader_kwargs=None,
        **trainer_kwargs
    ):
        if cycle_len < 1:
            raise ValueError("`cycle_len` must be >= 1.")
        if model_type not in {"linear", "mlp"}:
            raise ValueError("`model_type` must be one of {'linear', 'mlp'}.")

        futr_exog_list = list(futr_exog_list) if futr_exog_list is not None else []
        if cycle_index_col is not None and cycle_index_col not in futr_exog_list:
            futr_exog_list = futr_exog_list + [cycle_index_col]

        super().__init__(
            h=h,
            input_size=input_size,
            stat_exog_list=stat_exog_list,
            hist_exog_list=hist_exog_list,
            futr_exog_list=futr_exog_list,
            exclude_insample_y=exclude_insample_y,
            loss=loss,
            valid_loss=valid_loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            windows_batch_size=windows_batch_size,
            inference_windows_batch_size=inference_windows_batch_size,
            start_padding_enabled=start_padding_enabled,
            step_size=step_size,
            scaler_type=scaler_type,
            random_seed=random_seed,
            drop_last_loader=drop_last_loader,
            alias=alias,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            dataloader_kwargs=dataloader_kwargs,
            **trainer_kwargs
        )

        self.c_out = self.loss.outputsize_multiplier
        self.cycle_len = cycle_len
        self.cycle_index_col = cycle_index_col
        self.model_type = model_type
        self.d_model = d_model
        self.use_revin = use_revin

        self.cycle_queue = RecurrentCycle(cycle_len=cycle_len, channel_size=1)
        if self.model_type == "linear":
            self.model = nn.Linear(self.input_size, self.h * self.c_out)
        else:
            self.model = nn.Sequential(
                nn.Linear(self.input_size, self.d_model),
                nn.ReLU(),
                nn.Linear(self.d_model, self.h * self.c_out),
            )

    def _get_input_cycle_index(self, windows_batch, batch_size: int, device: torch.device):
        # Upstream expects an explicit `cycle_index` tensor in forward.
        # Reference:
        # https://github.com/ACAT-SCUT/CycleNet/blob/main/models/CycleNet.py
        # The README shows this is built as t mod W in the dataloader:
        # https://github.com/ACAT-SCUT/CycleNet/blob/main/README.md#model-implementation
        if self.cycle_index_col is None:
            return torch.zeros(batch_size, dtype=torch.long, device=device)

        futr_exog = windows_batch.get("futr_exog", None)
        if futr_exog is None or len(self.futr_exog_list) == 0:
            raise RuntimeError(
                "CycleNet expected `futr_exog` with the cycle index column, "
                "but none was found. Pass `cycle_index_col` as a future exogenous feature."
            )

        col_idx = self.futr_exog_list.index(self.cycle_index_col)
        start_idx = futr_exog[:, 0, col_idx]
        return torch.remainder(start_idx.long(), self.cycle_len)

    def forward(self, windows_batch):
        insample_y = windows_batch["insample_y"]  # [B, L, 1]
        batch_size = insample_y.shape[0]
        device = insample_y.device

        if self.use_revin:
            seq_mean = torch.mean(insample_y, dim=1, keepdim=True)
            seq_var = torch.var(insample_y, dim=1, keepdim=True, unbiased=False) + 1e-5
            x = (insample_y - seq_mean) / torch.sqrt(seq_var)
        else:
            x = insample_y

        cycle_start = self._get_input_cycle_index(
            windows_batch=windows_batch, batch_size=batch_size, device=device
        )
        input_cycle = self.cycle_queue(cycle_start, self.input_size)
        x = x - input_cycle

        y = self.model(x.permute(0, 2, 1)).permute(0, 2, 1)
        y = y.reshape(batch_size, self.h, self.c_out)

        output_cycle_start = torch.remainder(cycle_start + self.input_size, self.cycle_len)
        output_cycle = self.cycle_queue(output_cycle_start, self.h)
        y = y + output_cycle

        if self.use_revin:
            y = y * torch.sqrt(seq_var) + seq_mean

        return y
