# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.itransformer.ipynb.

# %% auto 0
__all__ = ['iTransformer']

# %% ../../nbs/models.itransformer.ipynb 6
import torch
import torch.nn as nn
import torch.nn.functional as F
from types import SimpleNamespace

from typing import Optional
from ..losses.pytorch import MAE
from ..common._base_model import BaseModel

from neuralforecast.common._modules import (
    TransEncoder,
    TransEncoderLayer,
    AttentionLayer,
    FullAttention,
    DataEmbedding_inverted,
    RevINMultivariate,
    Flatten_Head,
)


class itransformer_backbone(nn.Module):
    """iTransformer Forecaster Module"""
    
    def __init__(self, config):
        super().__init__()

        # RevIN normalization
        self.revin = config.revin
        if config.revin:
            self.revin_layer = RevINMultivariate(
                num_features=config.n_series,
                affine=config.revin_affine,
                subtract_last=config.revin_subtract_last,
            )
        
        # Embedding layer (inverted - operates on variate dimension)
        self.enc_embedding = DataEmbedding_inverted(
            config.input_size, config.hidden_size, config.dropout
        )
        
        # Transformer encoder
        self.encoder = TransEncoder(
            [
                TransEncoderLayer(
                    attention=AttentionLayer(
                        attention=FullAttention(
                            mask_flag=False, 
                            factor=config.factor, 
                            attention_dropout=config.dropout,
                        ),
                        hidden_size=config.hidden_size,
                        n_heads=config.n_heads,
                        d_keys=config.d_k,
                        d_values=config.d_v,
                    ),
                    hidden_size=config.hidden_size,
                    conv_hidden_size=config.linear_hidden_size,
                    dropout=config.dropout,
                    activation=F.gelu,
                )
                for l in range(config.n_layers)
            ],
            norm_layer=torch.nn.LayerNorm(config.hidden_size),
        )
        
        # Prediction head
        self.head = Flatten_Head(
            multivariate_head=config.multivariate_head,
            n_vars=config.n_series,
            nf=config.hidden_size,
            h=config.h,
            c_out=config.c_out,
            head_dropout=config.head_dropout,
        )

    def forward(self, x_enc: torch.Tensor, **kwargs):
        """
        x_enc: [batch_size x n_series x seq_len]
        """
        batch_size, n_series, seq_len = x_enc.shape
    
        if self.revin:
            x_enc = x_enc.permute(0, 2, 1)  # [B, L, N]
            x_enc = self.revin_layer(x_enc, "norm")
            x_enc = x_enc.permute(0, 2, 1)  # [B, N, L]
        
        # Embedding
        x_enc = x_enc.permute(0, 2, 1)  # [B, L, N]
        enc_in = self.enc_embedding(x_enc, None) # B L N -> B N E
        
        # Encoding
        enc_out, attns = self.encoder(enc_in, attn_mask=None) # B N E -> B N E
        
        # Projection to forecast horizon using Flatten_Head
        # [B, N, E] -> [B, N, 1, E] -> [B, N, H*C]
        enc_out = enc_out.unsqueeze(2)  # [B, N, 1, E]
        dec_out = self.head(enc_out)  # [B, N, H*c_out]
        
        # De-normalization with RevIN
        if self.revin:
            dec_out = dec_out.permute(0, 2, 1)  # [B, H*c_out, N]
            dec_out = self.revin_layer(dec_out, "denorm")
            dec_out = dec_out.permute(0, 2, 1)  # [B, N, H*c_out]
        
        return dec_out

# %% ../../nbs/models.itransformer.ipynb 8
class iTransformer(BaseModel):
    """iTransformer

    **Parameters:**<br>
    `h`: int, Forecast horizon. <br>
    `input_size`: int, autorregresive inputs size, y=[1,2,3,4] input_size=2 -> y_[t-2:t]=[1,2].<br>
    `n_series`: int, number of time-series.<br>
    `stat_exog_list`: str list, static exogenous columns.<br>
    `hist_exog_list`: str list, historic exogenous columns.<br>
    `futr_exog_list`: str list, future exogenous columns.<br>
    `exclude_insample_y`: bool=False, the model skips the autoregressive features y[t-input_size:t] if True.<br>
    `hidden_size`: int=512, dimension of the model.<br>
    `n_heads`: int=8, number of heads.<br>
    `n_layers`: int=2, number of encoder layers.<br>
    `linear_hidden_size`: int=2048, dimension of fully-connected layer.<br>
    `factor`: int=1, attention factor.<br>
    `dropout`: float=0.1, dropout rate.<br>
    `head_dropout`: float=0.0, dropout rate for projection head.<br>
    `multivariate_head`: bool=False, whether to use multivariate projection head.<br>
    `revin`: bool=True, whether to use RevIN normalization.<br>
    `revin_affine`: bool=False, whether to use affine transformation in RevIN.<br>
    `loss`: PyTorch module, instantiated train loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `valid_loss`: PyTorch module=`loss`, instantiated valid loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `max_steps`: int=1000, maximum number of training steps.<br>
    `learning_rate`: float=1e-3, Learning rate between (0, 1).<br>
    `num_lr_decays`: int=-1, Number of learning rate decays, evenly distributed across max_steps.<br>
    `early_stop_patience_steps`: int=-1, Number of validation iterations before early stopping.<br>
    `val_check_steps`: int=100, Number of training steps between every validation loss check.<br>
    `batch_size`: int=32, number of different series in each batch.<br>
    `valid_batch_size`: int=None, number of different series in each validation and test batch, if None uses batch_size.<br>
    `windows_batch_size`: int=32, number of windows to sample in each training batch, default uses all.<br>
    `inference_windows_batch_size`: int=32, number of windows to sample in each inference batch, -1 uses all.<br>
    `start_padding_enabled`: bool=False, if True, the model will pad the time series with zeros at the beginning, by input size.<br>
    `step_size`: int=1, step size between each window of temporal data.<br>
    `scaler_type`: str='identity', type of scaler for temporal inputs normalization see [temporal scalers](https://nixtla.github.io/neuralforecast/common.scalers.html).<br>
    `random_seed`: int=1, random_seed for pytorch initializer and numpy generators.<br>
    `drop_last_loader`: bool=False, if True `TimeSeriesDataLoader` drops last non-full batch.<br>
    `alias`: str, optional,  Custom name of the model.<br>
    `optimizer`: Subclass of 'torch.optim.Optimizer', optional, user specified optimizer instead of the default choice (Adam).<br>
    `optimizer_kwargs`: dict, optional, list of parameters used by the user specified `optimizer`.<br>
    `lr_scheduler`: Subclass of 'torch.optim.lr_scheduler.LRScheduler', optional, user specified lr_scheduler instead of the default choice (StepLR).<br>
    `lr_scheduler_kwargs`: dict, optional, list of parameters used by the user specified `lr_scheduler`.<br>
    `dataloader_kwargs`: dict, optional, list of parameters passed into the PyTorch Lightning dataloader by the `TimeSeriesDataLoader`. <br>
    `**trainer_kwargs`: int,  keyword trainer arguments inherited from [PyTorch Lighning's trainer](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html?highlight=trainer).<br>

    **References**<br>
    - [Yong Liu, Tengge Hu, Haoran Zhang, Haixu Wu, Shiyu Wang, Lintao Ma, Mingsheng Long. "iTransformer: Inverted Transformers Are Effective for Time Series Forecasting"](https://arxiv.org/abs/2310.06625)
    """

    # Class attributes
    EXOGENOUS_FUTR = False
    EXOGENOUS_HIST = False
    EXOGENOUS_STAT = False
    MULTIVARIATE = True
    RECURRENT = False

    def __init__(
        self,
        h,
        input_size,
        n_series,
        stat_exog_list=None,
        hist_exog_list=None,
        futr_exog_list=None,
        exclude_insample_y=False,
        n_heads: int = 8,
        n_layers: int = 2,
        factor: int = 1,
        hidden_size: int = 512,
        linear_hidden_size: int = 256,
        d_k: Optional[int] = None,
        d_v: Optional[int] = None,
        dropout: float = 0.1,
        head_dropout: float = 0.0,
        multivariate_head: bool = False,
        revin: bool = True,
        revin_affine: bool = False,
        revin_subtract_last: bool = True,
        start_padding_enabled=False,
        step_size: int = 1,
        scaler_type: str = "identity",
        random_seed: int = 1,
        drop_last_loader: bool = False,
        alias: Optional[str] = None,
        loss=MAE(),
        valid_loss=None,
        max_steps: int = 1000,
        learning_rate: float = 1e-3,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        windows_batch_size=32,
        inference_windows_batch_size: int = 32,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        dataloader_kwargs=None,
        **trainer_kwargs
    ):

        super(iTransformer, self).__init__(
            h=h,
            input_size=input_size,
            n_series=n_series,
            stat_exog_list=stat_exog_list,
            hist_exog_list=hist_exog_list,
            futr_exog_list=futr_exog_list,
            exclude_insample_y=exclude_insample_y,
            loss=loss,
            valid_loss=valid_loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            windows_batch_size=windows_batch_size,
            inference_windows_batch_size=inference_windows_batch_size,
            start_padding_enabled=start_padding_enabled,
            step_size=step_size,
            scaler_type=scaler_type,
            random_seed=random_seed,
            drop_last_loader=drop_last_loader,
            alias=alias,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            dataloader_kwargs=dataloader_kwargs,
            **trainer_kwargs
        )

        config = {key: value for key, value in self.hparams.items() 
                  if key != 'loss'}
        config['c_out'] = self.loss.outputsize_multiplier
        config = SimpleNamespace(**config)
    
        self.h = h
        self.n_series = n_series
        self.model = itransformer_backbone(config)

    def forward(self, windows_batch):
        x = windows_batch["insample_y"]  # [batch_size (B), input_size (L), n_series (N)]
        
        batch_size = x.shape[0]
        x_enc = x.permute(0, 2, 1)  # [batch_size (B), n_series (N), input_size (L)]
        
        forecast = self.model(x_enc=x_enc)  # [batch_size, n_series, horizon*c_out]
        
        forecast = forecast.view(batch_size, self.n_series, self.h, -1)  # [B, N, H, C]
        forecast = forecast.permute(0, 2, 3, 1).reshape(batch_size, self.h, -1)  # [B, H, C*N]
        
        return forecast
