# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.patchtst.ipynb.

# %% auto 0
__all__ = ['PatchTST_backbone', 'Flatten_Head', 'TSTEncoder', 'PatchTST']

# %% ../../nbs/models.patchtst.ipynb 5
import math
import numpy as np
from typing import Optional  # , Any, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import T5Config, T5EncoderModel, T5Model

from ..common._base_windows import BaseWindows
from ..common._instance_norm import RevIN
from ..common._positional_encodings import PositionalEncoding
from ..common._projections import ProjectionHead 
from ..common._tokenizers import Tokenizer
from ..common._t5_utils import CustomT5Stack, CustomT5Attention

from ..losses.pytorch import MAE


# %% ../../nbs/models.patchtst.ipynb 15
class PatchTST_backbone(nn.Module):
    """
    PatchTST_backbone
    """

    def __init__(
        self,
        config: dict,
        c_in: int,
        c_out: int,
        input_size: int,
        h: int,
        token_len: int,
        lag: int,
        stride: int,
        hidden_size: int,
        key_padding_mask: str = "auto",
        attn_mask: str = "bidirectional",
        pe: str = "zeros",
        learn_pe: bool = True,
        fc_dropout: float = 0.0,
        head_dropout=0,
        padding_patch=None,
        tokenizer_type='patch_fixed_length',
        head_type="flatten",
        individual=False,
        revin=True,
        affine=True,
        subtract_last=False,
    ):

        super().__init__()

        # RevIn
        self.revin = revin
        if self.revin:
            self.revin_layer = RevIN(c_in, affine=affine, subtract_last=subtract_last)

        # Patching
        token_num = int((input_size - token_len) / stride + 1)
        if padding_patch == "end":  # can be modified to general case
            token_num += 1
        self.tokenizer = Tokenizer(tokenizer_type,
                                   token_len=token_len,
                                   stride=stride,
                                   token_num=token_num,
                                   lag=lag,
                                   padding_patch=padding_patch,
                                   )

        # Backbone
        self.backbone = TSTEncoder(
            config,
            c_in,
            hidden_size,
            token_num=token_num,
            token_len=token_len,
            key_padding_mask=key_padding_mask,
            attn_mask=attn_mask,
            pe=pe,
            learn_pe=learn_pe,
        )

        # Head
        self.head_nf = hidden_size * token_num
        self.n_vars = c_in
        self.c_out = c_out
        self.head_type = head_type
        self.individual = individual
        
        proj_hd = ProjectionHead(
            self.individual,
            self.n_vars,
            self.head_nf,
            h,
            c_out,
            head_dropout,
        )

        if head_type == "flatten":
            proj_hd.flatten_head()  # Initialize layers in ProjectionHead
            self.head = proj_hd
        elif head_type == "residual_network":
            proj_hd.residual_network()  # Initialize layers in ProjectionHead
            self.head = proj_hd

    def forward(self, z):  # z: [bs x nvars x seq_len]
        # norm
        if self.revin:
            z = z.permute(0, 2, 1)
            z = self.revin_layer(z, "norm")
            z = z.permute(0, 2, 1)

        # tokenize input
        z = self.tokenizer.output_transform(z) 
        z = z.permute(0, 1, 3, 2)  # z: [bs x nvars x patch_len x patch_num]

        # model
        z = self.backbone(z)  # z: [bs x nvars x hidden_size x patch_num]
        #embeddings = z.clone() # WILLA ADDED THIS
        z = self.head(z)  # z: [bs x nvars x h]

        # denorm
        if self.revin:
            z = z.permute(0, 2, 1)
            z = self.revin_layer(z, "denorm")
            z = z.permute(0, 2, 1)
        return z
        #return z, embeddings # WILLA ADDED THIS

class TSTEncoder(nn.Module):  # i means channel-independent
    """
    TSTEncoder
    """

    def __init__(
        self,
        config,
        c_in,
        hidden_size,
        token_num,
        token_len,
        attn_dropout=0.0,
        dropout=0.0,
        act="gelu",
        key_padding_mask="auto",
        attn_mask="bidirectional",
        pe="zeros",
        learn_pe=True,
    ):

        super().__init__()

        self.attn_mask = attn_mask

        # Input encoding
        self.W_P = nn.Linear(
            token_len, hidden_size
        )  # Eq 1: projection of feature vectors onto a d-dim vector space

        # Positional encoding
        self.W_pos = PositionalEncoding(pe=pe).output(learn_pe, token_num, hidden_size)

        # Residual dropout
        self.dropout = nn.Dropout(dropout)

        # Encoder
        model_config = T5Config.from_dict(config)
        transformer_backbone = T5Model(model_config)
        transformer_backbone.encoder = CustomT5Stack(model_config, pe=pe)
        self.encoder = transformer_backbone.get_encoder()

        for layer_idx, layer in enumerate(self.encoder.block):
            if layer_idx==0:
                layer.layer[0].SelfAttention = CustomT5Attention(model_config, pe=pe)
        
        if config["enable_gradient_checkpointing"]==True:
            transformer_backbone.gradient_checkpointing_enable()

    def forward(self, x) -> torch.Tensor:  # x: [bs x nvars x patch_len x patch_num]

        n_vars = x.shape[1]
        # Input encoding
        x = x.permute(0, 1, 3, 2)  # x: [bs x nvars x patch_num x patch_len]
        x = self.W_P(x)  # x: [bs x nvars x patch_num x hidden_size]

        u = torch.reshape(
            x, (x.shape[0] * x.shape[1], x.shape[2], x.shape[3])
        )  # u: [bs * nvars x patch_num x hidden_size]
        u = self.dropout(u + self.W_pos)  

        # Encoder
        if self.attn_mask=='bidirectional':
            attn_mask = torch.ones(x.shape[0], u.shape[2], dtype=torch.long).to(x.device)
        elif self.attn_mask=='causal':
            attn_mask = torch.tril(torch.ones(x.shape[0], u.shape[2], dtype=torch.long, device=x.device))
            
        z = self.encoder(inputs_embeds=u, attention_mask=attn_mask)
        z = z.last_hidden_state
        z = torch.reshape(
            z, (-1, n_vars, z.shape[-2], z.shape[-1])
        )  # z: [bs x nvars x patch_num x hidden_size]
        z = z.permute(0, 1, 3, 2)  # z: [bs x nvars x hidden_size x patch_num]

        return z

# %% ../../nbs/models.patchtst.ipynb 17
class PatchTST(BaseWindows):
    """PatchTST

    The PatchTST model is an efficient Transformer-based model for multivariate time series forecasting.

    It is based on two key components:
    - segmentation of time series into windows (patches) which are served as input tokens to Transformer
    - channel-independence, where each channel contains a single univariate time series.

    **Parameters:**<br>
    `h`: int, Forecast horizon. <br>
    `input_size`: int, autorregresive inputs size, y=[1,2,3,4] input_size=2 -> y_[t-2:t]=[1,2].<br>
    `stat_exog_list`: str list, static exogenous columns.<br>
    `hist_exog_list`: str list, historic exogenous columns.<br>
    `futr_exog_list`: str list, future exogenous columns.<br>
    `exclude_insample_y`: bool=False, the model skips the autoregressive features y[t-input_size:t] if True.<br>
    `encoder_layers`: int, number of layers for encoder.<br>
    `n_heads`: int=16, number of multi-head's attention.<br>
    `hidden_size`: int=128, units of embeddings and encoders.<br>
    `linear_hidden_size`: int=256, units of linear layer.<br>
    `dropout`: float=0.1, dropout rate for residual connection.<br>
    `fc_dropout`: float=0.1, dropout rate for linear layer.<br>
    `head_dropout`: float=0.1, dropout rate for Flatten head layer.<br>
    `attn_dropout`: float=0.1, dropout rate for attention layer.<br>
    `patch_len`: int=32, length of patch. Note: patch_len = min(patch_len, input_size + stride).<br>
    `stride`: int=16, stride of patch.<br>
    `revin`: bool=True, bool to use RevIn.<br>
    `revin_affine`: bool=False, bool to use affine in RevIn.<br>
    `revin_substract_last`: bool=False, bool to use substract last in RevIn.<br>
    `activation`: str='ReLU', activation from ['gelu','relu'].<br>
    `learn_pos_embedding`: bool=True, bool to learn positional embedding.<br>
    `loss`: PyTorch module, instantiated train loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `valid_loss`: PyTorch module=`loss`, instantiated valid loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `max_steps`: int=1000, maximum number of training steps.<br>
    `learning_rate`: float=1e-3, Learning rate between (0, 1).<br>
    `num_lr_decays`: int=-1, Number of learning rate decays, evenly distributed across max_steps.<br>
    `early_stop_patience_steps`: int=-1, Number of validation iterations before early stopping.<br>
    `val_check_steps`: int=100, Number of training steps between every validation loss check.<br>
    `batch_size`: int=32, number of different series in each batch.<br>
    `valid_batch_size`: int=None, number of different series in each validation and test batch, if None uses batch_size.<br>
    `windows_batch_size`: int=1024, number of windows to sample in each training batch, default uses all.<br>
    `inference_windows_batch_size`: int=1024, number of windows to sample in each inference batch.<br>
    `start_padding_enabled`: bool=False, if True, the model will pad the time series with zeros at the beginning, by input size.<br>
    `step_size`: int=1, step size between each window of temporal data.<br>
    `scaler_type`: str='identity', type of scaler for temporal inputs normalization see [temporal scalers](https://nixtla.github.io/neuralforecast/common.scalers.html).<br>
    `random_seed`: int, random_seed for pytorch initializer and numpy generators.<br>
    `num_workers_loader`: int=os.cpu_count(), workers to be used by `TimeSeriesDataLoader`.<br>
    `drop_last_loader`: bool=False, if True `TimeSeriesDataLoader` drops last non-full batch.<br>
    `alias`: str, optional,  Custom name of the model.<br>
    `optimizer`: Subclass of 'torch.optim.Optimizer', optional, user specified optimizer instead of the default choice (Adam).<br>
    `optimizer_kwargs`: dict, optional, list of parameters used by the user specified `optimizer`.<br>
    `lr_scheduler`: Subclass of 'torch.optim.lr_scheduler.LRScheduler', optional, user specified lr_scheduler instead of the default choice (StepLR).<br>
    `lr_scheduler_kwargs`: dict, optional, list of parameters used by the user specified `lr_scheduler`.<br>
    `**trainer_kwargs`: int,  keyword trainer arguments inherited from [PyTorch Lighning's trainer](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html?highlight=trainer).<br>

    **References:**<br>
    -[Nie, Y., Nguyen, N. H., Sinthong, P., & Kalagnanam, J. (2022). "A Time Series is Worth 64 Words: Long-term Forecasting with Transformers"](https://arxiv.org/pdf/2211.14730.pdf)
    """

    # Class attributes
    SAMPLING_TYPE = "windows"
    EXOGENOUS_FUTR = False
    EXOGENOUS_HIST = False
    EXOGENOUS_STAT = False

    def __init__(
        self,
        h,
        input_size,
        stat_exog_list=None,
        hist_exog_list=None,
        futr_exog_list=None,
        exclude_insample_y=False,
        encoder_layers: int = 3,
        n_heads: int = 16,
        hidden_size: int = 128,
        linear_hidden_size: int = 256,
        dropout: float = 0.2,
        fc_dropout: float = 0.2,
        head_dropout: float = 0.0,
        attn_dropout: float = 0.0,
        token_len: int = 16,
        lag: int=1,
        stride: int = 8,
        revin: bool = True,
        revin_affine: bool = False,
        revin_subtract_last: bool = True,
        activation: str = "gated-gelu",
        key_padding_mask: str = "auto",
        batch_normalization: bool = False,
        learn_pos_embed: bool = True,
        loss=MAE(),
        valid_loss=None,
        max_steps: int = 5000,
        learning_rate: float = 1e-4,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        windows_batch_size=1024,
        inference_windows_batch_size: int = 1024,
        start_padding_enabled=False,
        step_size: int = 1,
        scaler_type: str = "identity",
        random_seed: int = 1,
        num_workers_loader: int = 0,
        drop_last_loader: bool = False,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        pe: str = "zeros", 
        tokenizer_type = 'patch_fixed_length',
        attn_mask: str = "bidirectional",
        head_type: str = "flatten", 
        **trainer_kwargs
    ):
        super(PatchTST, self).__init__(
            h=h,
            input_size=input_size,
            hist_exog_list=hist_exog_list,
            stat_exog_list=stat_exog_list,
            futr_exog_list=futr_exog_list,
            exclude_insample_y=exclude_insample_y,
            loss=loss,
            valid_loss=valid_loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            windows_batch_size=windows_batch_size,
            inference_windows_batch_size=inference_windows_batch_size,
            start_padding_enabled=start_padding_enabled,
            step_size=step_size,
            scaler_type=scaler_type,
            num_workers_loader=num_workers_loader,
            drop_last_loader=drop_last_loader,
            random_seed=random_seed,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            **trainer_kwargs
        )

        # Enforce correct patch_len, regardless of user input
        if tokenizer_type == 'lags':
            token_len=1
            stride=1
            padding_patch = None 
        elif 'patch' in tokenizer_type:
            token_len = min(input_size + stride, token_len)
            padding_patch = "end"  # Padding at the end

        c_out = self.loss.outputsize_multiplier

        # Fixed hyperparameters
        c_in = 1  # Always univariate
        individual = False  # Separate heads for each time series
        
        config={'num_layers': encoder_layers,
            'num_heads': n_heads,
            'num_decoder_layers' : 0,
            'd_model': hidden_size,
            'd_kv': hidden_size // n_heads,
            'd_ff': linear_hidden_size,
            'dropout_rate': dropout,
            'feed_forward_proj': activation,
            #'relative_attention_num_buckets': 32,
            #'has_relative_attention_bias': False,
            'enable_gradient_checkpointing': False,
            'use_cache': False, 
            'is_decoder': False,
            }

        self.model = PatchTST_backbone(
            config=config,
            c_in=c_in,
            c_out=c_out,
            input_size=input_size,
            h=h,
            token_len=token_len,
            lag=lag,
            stride=stride,
            hidden_size=hidden_size,
            key_padding_mask=key_padding_mask,
            attn_mask=attn_mask,
            pe=pe,
            learn_pe=learn_pos_embed,
            fc_dropout=fc_dropout,
            head_dropout=head_dropout,
            padding_patch=padding_patch,
            tokenizer_type=tokenizer_type,
            head_type=head_type,
            revin=revin,
            affine=revin_affine,
            subtract_last=revin_subtract_last,
        )

    def forward(self, windows_batch):  # x: [batch, input_size]

        # Parse windows_batch
        insample_y = windows_batch["insample_y"]
        # insample_mask = windows_batch['insample_mask']
        # hist_exog     = windows_batch['hist_exog']
        # stat_exog     = windows_batch['stat_exog']
        # futr_exog     = windows_batch['futr_exog']

        # Add dimension for channel
        x = insample_y.unsqueeze(-1)  # [Ws,L,1]

        x = x.permute(0, 2, 1)  # x: [Batch, 1, input_size]
        x = self.model(x)
        #x, embeddings = self.model(x) # Willa added 
        x = x.reshape(x.shape[0], self.h, -1)  # x: [Batch, h, c_out]

        # Domain map
        forecast = self.loss.domain_map(x)
        
        return forecast
        #return forecast, embeddings # Willa added
