# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.patchtst.ipynb.

# %% auto 0
__all__ = ['SinCosPosEncoding', 'Transpose', 'get_activation_fn', 'PositionalEncoding', 'Coord2dPosEncoding',
           'Coord1dPosEncoding', 'positional_encoding', 'PatchTST_backbone', 'Flatten_Head', 'TSTiEncoder',
           'TSTEncoder', 'TSTEncoderLayer', 'PatchTST']

# %% ../../nbs/models.patchtst.ipynb 5
from typing import Optional
from types import SimpleNamespace

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..common._base_model import BaseModel
from ..common._modules import RevINMultivariate, Flatten_Head, Patching, PositionalEncoding
from ..common._infini import MultiheadAttention

from ..losses.pytorch import MAE

# %% ../../nbs/models.patchtst.ipynb 9
class Transpose(nn.Module):
    """
    Transpose
    """

    def __init__(self, *dims, contiguous=False):
        super().__init__()
        self.dims, self.contiguous = dims, contiguous

    def forward(self, x):
        if self.contiguous:
            return x.transpose(*self.dims).contiguous()
        else:
            return x.transpose(*self.dims)

def get_activation_fn(activation):
    if callable(activation):
        return activation()
    elif activation.lower() == "relu":
        return nn.ReLU()
    elif activation.lower() == "gelu":
        return nn.GELU()
    raise ValueError(
        f'{activation} is not available. You can use "relu", "gelu", or a callable'
    )

# %% ../../nbs/models.patchtst.ipynb 13
class PatchTST_backbone(nn.Module):
    """
    PatchTST_backbone
    """
    def __init__(
        self,
        config,
    ):

        super().__init__()

        self.hidden_size = config.hidden_size
        self.patch_len = config.patch_len

        self.revin = config.revin
        if config.revin:
            self.revin_layer = RevINMultivariate(
                num_features=config.n_series, 
                affine=config.revin_affine, 
                subtract_last=config.revin_subtract_last,
            )

        self.padding_patch = config.padding_patch
        patch_num = int((config.input_size - config.patch_len) / config.stride + 1)
        if config.padding_patch == "end":  # can be modified to general case
            self.padding_patch_layer = nn.ReplicationPad1d((0, config.stride))
            patch_num += 1
        self.patch_num = patch_num

        self.tokenizer = Patching(
            patch_len=config.patch_len, 
            stride=config.stride,
        )

        self.W_P = nn.Linear(
            config.patch_len, config.hidden_size
        )  # Eq 1: projection of feature vectors onto a d-dim vector space

        # Positional encoding
        self.W_pos = PositionalEncoding(
            pe_type=config.pe_type,
            hidden_size=config.hidden_size,
            learn_pe=config.learn_pe,
        )
        # Residual dropout
        self.dropout = nn.Dropout(config.dropout)

        self.encoder = TSTEncoder(config=config)

        # Prediction Head
        self.head = Flatten_Head(
            multivariate_head=config.multivariate_head,
            n_vars=config.n_series,
            nf=config.hidden_size * patch_num,
            h=config.h,
            c_out=config.c_out,
            head_dropout=config.head_dropout,
        )

    def forward(self, x_enc : torch.Tensor):  # z: [bs x nvars x seq_len]

        batch_size, n_channels, seq_len = x_enc.shape

        # Normalization (applied over axis=1)
        if self.revin:
            x_enc = x_enc.permute(0, 2, 1) # [batch_size x seq_len x n_channel]
            x_enc = self.revin_layer(x_enc, "norm")
            x_enc = x_enc.permute(0, 2, 1) # [batch_size x n_channel x seq_len]
        
        # Patching
        if self.padding_patch == "end":
            x_enc = self.padding_patch_layer(x_enc) 
        x_enc = self.tokenizer(x=x_enc) # [batch_size x n_channels x n_patch x patch_len]

        # Embeddings
        x_enc = self.W_P(x_enc) # [batch_size x n_channels x n_patch x d_model]
        x_enc += self.W_pos(x_enc) # [batch_size x n_channels x n_patch x d_model]
        
        x_enc = x_enc.reshape(
            (batch_size * n_channels, self.patch_num, self.hidden_size)) # [batch_size*n_channels, n_patch, d_model]
        x_enc = self.dropout(x_enc) # [batch_size*n_channels, n_patch, d_model]

        # Encoder
        enc_out = self.encoder(src=x_enc, n_channels=n_channels)  # z: [bs x nvars x patch_num x hidden_size]
        enc_out = enc_out.reshape(
            (batch_size, n_channels, self.patch_num, self.hidden_size)
        ) # [batch_size, n_channels, n_patch, d_model]
        
        # Decoder
        dec_out = self.head(enc_out)  # z: [bs x nvars x h]

        # De-Normalization
        if self.revin:
            dec_out = dec_out.permute(0, 2, 1) # [batch_size x horizon*c_out x n_channel]
            dec_out = self.revin_layer(dec_out, "denorm")
            dec_out = dec_out.permute(0, 2, 1) # [batch_size x n_channel x horizon*c_out]

        return dec_out

class TSTEncoder(nn.Module):
    """
    TSTEncoder
    """
    def __init__(
        self,
        config,
    ):
        super().__init__()

        if config.infini_mixer_type == 'betas':
            if config.layerwise_beta:
                beta = None
            else:
                # Create a shared beta
                if config.channelwise_beta:
                    beta = nn.Parameter(torch.rand((1, config.n_series, config.n_heads, 1, 1))*1e-2)
                else:
                    beta = nn.Parameter(torch.rand((1, 1, config.n_heads, 1, 1))*1e-2)
                # Adjust the values to ensure they sum to 0
                with torch.no_grad():
                    beta -= beta.mean(dim=2, keepdim=True)
        else:
            beta=None

        self.layers = nn.ModuleList(
            [
                TSTEncoderLayer(
                    config=config,
                    beta=beta,
                )
                for i in range(config.n_layers)
            ]
        )
        self.res_attention = config.res_attention

    def forward(
        self,
        src: torch.Tensor,
        n_channels: int,
        key_padding_mask: Optional[torch.Tensor] = None,
        attn_mask: Optional[torch.Tensor] = None,
    ):
        output = src
        scores = None
        if self.res_attention:
            for mod in self.layers:
                output, scores = mod(
                    src=output,
                    n_channels=n_channels,
                    prev=scores,
                    key_padding_mask=key_padding_mask,
                    attn_mask=attn_mask,
                )
            return output
        else:
            for mod in self.layers:
                output = mod(
                    src=output, 
                    n_channels=n_channels,
                    key_padding_mask=key_padding_mask, 
                    attn_mask=attn_mask
                )
            return output

class TSTEncoderLayer(nn.Module):
    """
    TSTEncoderLayer
    """
    def __init__(
        self,
        config,
        beta: Optional[torch.Tensor] = None,
    ):
        super().__init__()

        # Multi-Head attention
        self.res_attention = config.res_attention
        self.self_attn = MultiheadAttention(
            config=config,
            beta=beta,
        )

        # Add & Norm
        self.dropout_attn = nn.Dropout(config.dropout)
        if "batch" in config.norm.lower():
            self.norm_attn = nn.Sequential(
                Transpose(1, 2), nn.BatchNorm1d(config.hidden_size), Transpose(1, 2)
            )
        else:
            self.norm_attn = nn.LayerNorm(config.hidden_size)

        # Position-wise Feed-Forward
        self.ff = nn.Sequential(
            nn.Linear(config.hidden_size, config.linear_hidden_size, bias=True), # bias hard-coded in PatchTST
            get_activation_fn(config.activation),
            nn.Dropout(config.dropout),
            nn.Linear(config.linear_hidden_size, config.hidden_size, bias=True), # bias hard-coded in PatchTST
        )

        # Add & Norm
        self.dropout_ffn = nn.Dropout(config.dropout)
        if "batch" in config.norm.lower():
            self.norm_ffn = nn.Sequential(
                Transpose(1, 2), nn.BatchNorm1d(config.hidden_size), Transpose(1, 2)
            )
        else:
            self.norm_ffn = nn.LayerNorm(config.hidden_size)

        self.pre_norm = config.pre_norm
        self.store_attn = config.store_attn

    def forward(
        self,
        src: torch.Tensor,
        n_channels: int,
        prev: Optional[torch.Tensor] = None,
        key_padding_mask: Optional[torch.Tensor] = None,
        attn_mask: Optional[torch.Tensor] = None,
    ):  # -> Tuple[torch.Tensor, Any]:

        # Multi-Head attention sublayer
        if self.pre_norm:
            src = self.norm_attn(src)
        ## Multi-Head attention
        if self.res_attention:
            src2, attn, scores = self.self_attn(
                n_channels=n_channels,
                Q=src,
                K=src,
                V=src,
                prev=prev,
                key_padding_mask=key_padding_mask,
                attn_mask=attn_mask,
            )
        else:
            src2, attn = self.self_attn(
                n_channels=n_channels,
                Q=src,
                K=src,
                V=src,
                key_padding_mask=key_padding_mask,
                attn_mask=attn_mask,
            )
        if self.store_attn:
            self.attn = attn
        ## Add & Norm
        src = src + self.dropout_attn(
            src2
        )  # Add: residual connection with residual dropout
        if not self.pre_norm:
            src = self.norm_attn(src)

        # Feed-forward sublayer
        if self.pre_norm:
            src = self.norm_ffn(src)
        ## Position-wise Feed-Forward
        src2 = self.ff(src)
        ## Add & Norm
        src = src + self.dropout_ffn(
            src2
        )  # Add: residual connection with residual dropout
        if not self.pre_norm:
            src = self.norm_ffn(src)

        if self.res_attention:
            return src, scores
        else:
            return src

# %% ../../nbs/models.patchtst.ipynb 15
class PatchTSTMultivariate(BaseModel):
    """PatchTST

    The PatchTST model is an efficient Transformer-based model for multivariate time series forecasting.

    It is based on two key components:
    - segmentation of time series into windows (patches) which are served as input tokens to Transformer
    - channel-independence, where each channel contains a single univariate time series.

    **Parameters:**<br>
    `h`: int, Forecast horizon. <br>
    `input_size`: int, autorregresive inputs size, y=[1,2,3,4] input_size=2 -> y_[t-2:t]=[1,2].<br>
    `stat_exog_list`: str list, static exogenous columns.<br>
    `hist_exog_list`: str list, historic exogenous columns.<br>
    `futr_exog_list`: str list, future exogenous columns.<br>
    `exclude_insample_y`: bool=False, the model skips the autoregressive features y[t-input_size:t] if True.<br>
    `encoder_layers`: int, number of layers for encoder.<br>
    `n_heads`: int=16, number of multi-head's attention.<br>
    `hidden_size`: int=128, units of embeddings and encoders.<br>
    `linear_hidden_size`: int=256, units of linear layer.<br>
    `dropout`: float=0.1, dropout rate for residual connection.<br>
    `head_dropout`: float=0.1, dropout rate for Flatten head layer.<br>
    `attn_dropout`: float=0.1, dropout rate for attention layer.<br>
    `patch_len`: int=32, length of patch. Note: patch_len = min(patch_len, input_size + stride).<br>
    `stride`: int=16, stride of patch.<br>
    `revin`: bool=True, bool to use RevIn.<br>
    `revin_affine`: bool=False, bool to use affine in RevIn.<br>
    `revin_subtract_last`: bool=False, bool to use substract last in RevIn.<br>
    `activation`: str='ReLU', activation from ['gelu','relu'].<br>
    `res_attention`: bool=False, bool to use residual attention.<br>
    `batch_normalization`: bool=False, bool to use batch normalization.<br>
    `loss`: PyTorch module, instantiated train loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `valid_loss`: PyTorch module=`loss`, instantiated valid loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `max_steps`: int=1000, maximum number of training steps.<br>
    `learning_rate`: float=1e-3, Learning rate between (0, 1).<br>
    `num_lr_decays`: int=-1, Number of learning rate decays, evenly distributed across max_steps.<br>
    `early_stop_patience_steps`: int=-1, Number of validation iterations before early stopping.<br>
    `val_check_steps`: int=100, Number of training steps between every validation loss check.<br>
    `batch_size`: int=32, number of different series in each batch.<br>
    `valid_batch_size`: int=None, number of different series in each validation and test batch, if None uses batch_size.<br>
    `windows_batch_size`: int=1024, number of windows to sample in each training batch, default uses all.<br>
    `inference_windows_batch_size`: int=1024, number of windows to sample in each inference batch.<br>
    `start_padding_enabled`: bool=False, if True, the model will pad the time series with zeros at the beginning, by input size.<br>
    `step_size`: int=1, step size between each window of temporal data.<br>
    `scaler_type`: str='identity', type of scaler for temporal inputs normalization see [temporal scalers](https://nixtla.github.io/neuralforecast/common.scalers.html).<br>
    `random_seed`: int, random_seed for pytorch initializer and numpy generators.<br>
    `drop_last_loader`: bool=False, if True `TimeSeriesDataLoader` drops last non-full batch.<br>
    `alias`: str, optional,  Custom name of the model.<br>
    `optimizer`: Subclass of 'torch.optim.Optimizer', optional, user specified optimizer instead of the default choice (Adam).<br>
    `optimizer_kwargs`: dict, optional, list of parameters used by the user specified `optimizer`.<br>
    `lr_scheduler`: Subclass of 'torch.optim.lr_scheduler.LRScheduler', optional, user specified lr_scheduler instead of the default choice (StepLR).<br>
    `lr_scheduler_kwargs`: dict, optional, list of parameters used by the user specified `lr_scheduler`.<br>
    `dataloader_kwargs`: dict, optional, list of parameters passed into the PyTorch Lightning dataloader by the `TimeSeriesDataLoader`. <br>
    `**trainer_kwargs`: int,  keyword trainer arguments inherited from [PyTorch Lighning's trainer](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html?highlight=trainer).<br>

    **References:**<br>
    -[Nie, Y., Nguyen, N. H., Sinthong, P., & Kalagnanam, J. (2022). "A Time Series is Worth 64 Words: Long-term Forecasting with Transformers"](https://arxiv.org/pdf/2211.14730.pdf)
    """

    # Class attributes
    EXOGENOUS_FUTR = False
    EXOGENOUS_HIST = False
    EXOGENOUS_STAT = False
    MULTIVARIATE = True  # If the model produces multivariate forecasts (True) or univariate (False)
    RECURRENT = (
        False  # If the model produces forecasts recursively (True) or direct (False)
    )

    def __init__(
        self,
        h,
        input_size,
        n_series,
        stat_exog_list=None,
        hist_exog_list=None,
        futr_exog_list=None,
        exclude_insample_y=False,
        # Transformer / Mixer config
        infini_mixer_type: str = "none",
        infini_memory_type: str = "retrieval",
        infini_channel_weight_type: str = "uniform",
        infini_channel_exclusion: bool = False,
        layerwise_beta: bool = True,
        channelwise_beta: bool = False,
        n_layers: int = 4,
        n_heads: int = 4,
        hidden_size: int = 256,
        linear_hidden_size: int = 1024,
        d_k: int = 32, 
        d_v: int = 32,
        dropout: float = 0.0,
        attn_dropout: float = 0.0,
        head_dropout: float = 0.0,
        proj_dropout: float = 0.0,
        patch_len: int = 8,
        stride: int = 8,
        revin: bool = True,
        revin_affine: bool = False,
        revin_subtract_last: bool = True,
        mlpmixer_hidden_size: int = 128,
        mlpmixer_n_layers: int = 3,
        mlpmixer_dropout: float = 0.1,
        multivariate_head: bool = False,
        pe_type: str = "sincos",
        learn_pe: bool = False,
        activation: str = "gelu",
        res_attention: bool = True,
        batch_normalization: bool = False,
        padding_patch = "end",
        start_padding_enabled=False,
        step_size: int = 1,
        scaler_type: str = "identity",
        random_seed: int = 1,
        drop_last_loader: bool = False,
        alias: Optional[str] = None,
        # Optimization and training
        loss=MAE(),
        valid_loss=None,
        max_steps: int = 5000,
        learning_rate: float = 1e-4,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        windows_batch_size=1024,
        inference_windows_batch_size: int = 1024,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        dataloader_kwargs=None,
        **trainer_kwargs
    ):
        super(PatchTSTMultivariate, self).__init__(
            h=h,
            input_size=input_size,
            n_series=n_series,
            stat_exog_list=stat_exog_list,
            hist_exog_list=hist_exog_list,
            futr_exog_list=futr_exog_list,
            exclude_insample_y=exclude_insample_y,
            loss=loss,
            valid_loss=valid_loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            windows_batch_size=windows_batch_size,
            inference_windows_batch_size=inference_windows_batch_size,
            start_padding_enabled=start_padding_enabled,
            step_size=step_size,
            scaler_type=scaler_type,
            random_seed=random_seed,
            drop_last_loader=drop_last_loader,
            alias=alias,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            dataloader_kwargs=dataloader_kwargs,
            **trainer_kwargs
        )

        # Enforce correct patch_len, regardless of user input
        patch_len = min(input_size + stride, patch_len)

        config = {key: value for key, value in self.hparams.items() 
                  if key != 'loss'
        }
        config['c_out'] = self.loss.outputsize_multiplier
        config['patch_len'] = patch_len
        config['norm'] = "BatchNorm"
        config['store_attn'] = False
        config['max_seq_len'] = 1024
        config['key_padding_mask'] = "auto"
        config['padding_var'] = None
        config['attn_mask'] = None
        config['qkv_bias'] = True # hardcoded in PatchTST
        config['pre_norm'] = batch_normalization
        config = SimpleNamespace(**config)

        self.h = h
        self.n_series = n_series
        self.model = PatchTST_backbone(config=config)

    def forward(self, windows_batch):  # x: [batch, input_size]
        x = windows_batch[
            "insample_y"
        ]  #   [batch_size (B), input_size (L), n_series (N)]
        
        batch_size = x.shape[0]
        x_enc = x.permute(0, 2, 1) # [batch_size (B), n_series (N), input_size (L)]
        forecast = self.model(x_enc)

        forecast = forecast.view(batch_size, self.n_series, self.h, -1)
        forecast = forecast.permute(0, 2, 3, 1).reshape(batch_size, self.h, -1) # [batch_size, horizon, c_out*n_series] 
        # output is expected in this shape. tsmixer and other neuralforecast multivariate models' decoder output is already in shape # [batch_size, horizon*c_out, n_series] so skipping to forecast.reshape(batch_size, self.h, -1) is valid for those models. 

        return forecast
